# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f022317d32278cffac3762bf3782e4e8521681697bfe94b5d2bd79670a8fcf0d0b5e68070bbdf77664a72d33a97ab67ea244463ff789a679a1463e03354625a

test:
  secret_key_base: b44de64107a2c4e1566e88697d80ce189816c72bfeb3d4cd1a2d18e79faa692787308084a6f30e5df8b6688cb8e9657ecb703839ee9fefbdd8dd7d5b72b56f4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
